var occupation=[ 'DOCTOR',
'TEACHER',
'FIRE',
'SOLDIER',
'POLICE',
'NURSE',
'BANKER',
'CIVIL',
'SUPERVISOR',
'ATTENDANT',
'LAWYER',
'HOUSEKEEPER',
'CHEF',
'WAITRESS',
'CLERK',
'DIRECTOR',
'SELF EMPLOYED',
'ACCOUNTANT',
'MANAGER',
'SECURITY',
'WATCHMAN',
'electrician',
'DRIVER',
'MECHANIC',
'CASHIER',
'OPERATOR',
'RECEPTIONIST',
'PILOT',
'CONSTABLE',
'SERGEANT',
'SPECIALIST',
'ANALYST',
'OFFICER',
'CONSULTANT',
'CONTRACTOR',
'CUSTOMER'].sort();

// Query Builder Rule Definitions
$('#builder-basic').queryBuilder({
  plugins: ['bt-tooltip-errors'],

  filters: [
    {
      id: 'ACCOUNT_NUMBER',
      label: 'Account Number',
      type: 'integer',
      input: 'number',
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    },
    {
      id: 'CI_ARREARS',
      label: 'Arrears(Loans)',
      type: 'integer',
      input: 'number',
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    },
    {
      id: 'CI_MINIMUMAMTDUE',
      label: 'Mininum Payment(Cards)',
      type: 'integer',
      input: 'number',
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    },
    {
      id: 'CI_CURRENTBAL',
      label: 'Current Balance',
      type: 'integer',
      input: 'number',
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    },
    {
      id: 'CI_OCCUPATION',
      label: 'Occupation',
      type: 'integer',
      input: 'select',
      values: occupation,
      operators: ['contains', 'not_contains'],
    }, {
      id: 'CI_CURRENCY',
      label: 'Currency',
      type: 'integer',
      input: 'select',
      values: [
        'GBP',
        'USD',
        'CAD',
        'JMD',
      ],
      operators: ['contains', 'not_contains'],
    }, {
      id: 'CI_PAYMENTDUEDATE',
      label: 'Payment Due Date',
      type: 'date',
      validation: {
        format: 'DD/MMM/YYYY',
      },
      plugin: 'datepicker',
      plugin_config: {
        format: '\'dd/M/yyyy\'',
        autoclose: true,
      },
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    },
    {
      id: 'CI_DATEOFBIRTH',
      label: 'Date of Birth',
      type: 'date',
      validation: {
        format: 'DD/MMM/YYYY',
      },
      plugin: 'datepicker',
      plugin_config: {
        format: '\'dd/M/yyyy\'',
        autoclose: true,
      },
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    },
    {
      id: 'CI_DPD',
      label: 'Days Past Due',
      type: 'integer',
      input: 'number',
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    },
    {
      id: 'CI_TRN_SSN',
      label: 'TRN',
      type: 'string',
      input: 'text',
      validation: {
        format: /^\d{9}?$/,
        messages: {
          format: 'A TRN Contains 9 Digits',
        },
      },
      operators: ['contains', 'not_contains'],
    }, {
      id: 'CI_TOTALEXPOSURE',
      label: 'Total Exposure',
      type: 'integer',
      input: 'number',
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    }, {
      id: 'CI_BROKENPROMISE',
      label: 'Broken Promise',
      type: 'integer',
      input: 'number',
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    }, {
      id: 'PROMISEAMOUNT',
      label: 'Promise to Pay',
      type: 'integer',
      input: 'number',
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    }, {
      id: 'CI_PRINCIPALBALANCEOUTSTANDING',
      label: 'Principal Balance Outstanding',
      type: 'double',
      input: 'number',
      operators: ['equal', 'not_equal', 'greater', 'greater_or_equal', 'between', 'not_between', 'less', 'less_or_equal'],
    }, {
      id: 'ACCOUNTTYPE',
      label: 'Product Type',
      type: 'integer',
      input: 'select',
      values: {
        'CARD': 'CARD',
        'LOAN': 'LOAN',
      },
      operators: ['contains', 'not_contains'],
    }, {
      id: 'CI_NATUREOFADVANCE',
      label: 'Nature of Advance',
      type: 'integer',
      input: 'select',
      values: {
        'SECURED': 'SECURED',
        'UNSECURED': 'UNSECURED',
      },
      operators: ['equal', 'not_equal'],
    }, {
      id: 'CI_SOLID',
      label: 'SOL ID',
      type: 'string',
      input: 'text',
      validation: {
        format: /^\d{3}?$/,
        messages: {
          format: 'Only 3 Digits are allowed.',
        },
      },
      operators: ['contains', 'not_contains'],
    }, {
      id: 'ACCSTATUS',
      label: 'Account Status',
      type: 'integer',
      input: 'select',
      values: [
        'D015',
        'D030',
        'D060',
        'D090',
        'BLBD',
        'WOFF',
      ],
      operators: ['contains', 'not_contains'],
    }],


});

